name: Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  coverage:
    uses: apidepth-io/apidepth-tooling/.github/workflows/coverage-python.yml@main
    with:
      source: "apidepth"
      install-extras: "dev"
